# Generated by Django 4.1.3 on 2022-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.BigIntegerField(verbose_name='telefone'),
        ),
    ]
